server:
  port: 18086
# 应用名称：client
spring:
  application:
    name: cart
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-wait: -1
          max-idle: 8
          enabled: true

# 注册到我们本地的eureka注册中心，端口是10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/