server:
  port: 18082
# 应用名称：client
spring:
  application:
    name: product2
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-wait: -1
          max-idle: 8
          enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000 # 连接超时时间 默认值：10000毫秒
            readTimeout: 4000 # 读取超时时间 默认值：60000毫秒

# 注册到我们本地的eureka注册中心，端口是10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/


